require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
